=== ne1947111/sem3html/CIA_XSL/xml/menu.dtd
<!ELEMENT menu (category)+>
<!ATTLIST menu xmlns CDATA #FIXED ''>

<!ELEMENT category (type,fooditem+)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT fooditem (AvgRating,Cuisine,Description,FoodName,ItemCode, PriceForFull,PriceForHalf,TimeOfServe, Image?)>

<!ELEMENT AvgRating (#PCDATA)>

<!ELEMENT Cuisine (#PCDATA)>
<!ATTLIST Cuisine  xmlns CDATA #FIXED ''>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT FoodName (#PCDATA)>

<!ELEMENT ItemCode (#PCDATA)>
<!ATTLIST ItemCode xmlns CDATA #FIXED ''>

<!ELEMENT PriceForFull (#PCDATA)>
<!ATTLIST PriceForFull xmlns CDATA #FIXED '' null NMTOKEN #IMPLIED>

<!ELEMENT PriceForHalf (#PCDATA)>
<!ATTLIST PriceForHalf xmlns CDATA #FIXED ''>

<!ELEMENT TimeOfServe (#PCDATA)>
<!ATTLIST TimeOfServe xmlns CDATA #FIXED ''>

<!ELEMENT Image (#PCDATA)>
<!ATTLIST Image xmlns CDATA #FIXED ''>

=== ne1947111/sem3html/Lab 11/xml/menu.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE menu SYSTEM "menu.dtd"><menu><category><type>Main Course</type><fooditem><AvgRating>3.8</AvgRating><Cuisine>Indian</Cuisine><Description>Paneer tikka masala is an Indian dish of marinated paneer cheese served in a spiced gravy.</Description><FoodName>Paneer Masala</FoodName><ItemCode>C101</ItemCode><PriceForFull>150</PriceForFull><PriceForHalf>80</PriceForHalf><TimeOfServe>Lunch/Dinner</TimeOfServe><Image>paneer.jpg</Image></fooditem><fooditem><AvgRating>3.8</AvgRating><Cuisine>Indian</Cuisine><Description>Mushroom masala is a delicious Indian curry made with mushrooms, onions, tomatoes, spices &amp; herbs</Description><FoodName>Mushroom Masala</FoodName><ItemCode>C102</ItemCode><PriceForFull>130</PriceForFull><PriceForHalf>70</PriceForHalf><TimeOfServe>Lunch/Dinner</TimeOfServe><Image>mushroom.jpg</Image></fooditem><fooditem><AvgRating>4.4</AvgRating><Cuisine>Indian</Cuisine><Description>Jeera Aloo is a typical vegetarian Indian dish which is often served as a side dish and normally goes well with hot puris, chapatti, roti or dal</Description><FoodName>Jeera Aloo</FoodName><ItemCode>C103</ItemCode><PriceForFull>130</PriceForFull><PriceForHalf>70</PriceForHalf><TimeOfServe>Lunch</TimeOfServe><Image>aloo.jpg</Image></fooditem><fooditem><AvgRating>4</AvgRating><Cuisine>Chinese</Cuisine><Description>inherits the recipe from paneer kadai with same spice masala but with mixed vegetables.</Description><FoodName>Veg Kadai</FoodName><ItemCode>C104</ItemCode><PriceForFull>150</PriceForFull><PriceForHalf>80</PriceForHalf><TimeOfServe>Lunch</TimeOfServe><Image>vegkadai.jpg</Image></fooditem><fooditem><AvgRating>4</AvgRating><Cuisine>Chinese</Cuisine><Description>Tender cauliflower florets cooked in a spicy tomato sauce.</Description><FoodName>Gobi Masala</FoodName><ItemCode>C105</ItemCode><PriceForFull>130</PriceForFull><PriceForHalf>70</PriceForHalf><TimeOfServe>Dinner</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>3.8</AvgRating><Cuisine>Indian</Cuisine><Description>made using raw kidney beans which are soaked and then cooked with onions, tomatoes and a special blend of spices</Description><FoodName>Rajma Masala</FoodName><ItemCode>C106</ItemCode><PriceForFull>110</PriceForFull><PriceForHalf>60</PriceForHalf><TimeOfServe>Lunch/Dinner</TimeOfServe><Image>rajma.jpg</Image></fooditem><fooditem><AvgRating>4.8</AvgRating><Cuisine>Indian</Cuisine><Description>Indian potato curry known as aloo curry is a side dish made of potatoes, onions, tomatoes, spices &amp; herbs.</Description><FoodName>Aloo Curry</FoodName><ItemCode>C107</ItemCode><PriceForFull>90</PriceForFull><PriceForHalf>50</PriceForHalf><TimeOfServe>Dinner</TimeOfServe><Image>.</Image></fooditem></category><category><type>Dessert</type><fooditem><AvgRating>4.8</AvgRating><Cuisine>.</Cuisine><Description>Ice cream is a sweetened frozen food made from dairy milk or cream and is flavoured with a sweetener</Description><FoodName>Ice Cream</FoodName><ItemCode>D101</ItemCode><PriceForFull>40</PriceForFull><PriceForHalf>20</PriceForHalf><TimeOfServe>Any time</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>3.8</AvgRating><Cuisine>.</Cuisine><Description>a carrot-based sweet dessert pudding</Description><FoodName>Carrot Halwa</FoodName><ItemCode>D102</ItemCode><PriceForFull>50</PriceForFull><PriceForHalf>25</PriceForHalf><TimeOfServe>Breakfast</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>4.2</AvgRating><Cuisine>.</Cuisine><Description>A classic food prepared from semolina, sugar, ghee and milk</Description><FoodName>Kesari</FoodName><ItemCode>D103</ItemCode><PriceForFull>40</PriceForFull><PriceForHalf>25</PriceForHalf><TimeOfServe>Breakfast</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>3.5</AvgRating><Cuisine>.</Cuisine><Description>dish consisting of various kinds of fruit, sometimes served in a liquid, either their own juices or a syrup.</Description><FoodName>Fruit Salad</FoodName><ItemCode>D104</ItemCode><PriceForFull>50</PriceForFull><PriceForHalf>30</PriceForHalf><TimeOfServe>Lunch/Dinner</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>4.5</AvgRating><Cuisine>.</Cuisine><Description>drink that is usually made by blending milk, ice cream, and flavorings or sweeteners such as butterscotch, caramel sauce, chocolate syrup, fruit syrup, or whole fruit into a thick, sweet, cold mixture.</Description><FoodName>Milkshake</FoodName><ItemCode>D105</ItemCode><PriceForFull>80</PriceForFull><PriceForHalf>45</PriceForHalf><TimeOfServe>Lunch/Dinner</TimeOfServe><Image>.</Image></fooditem></category><category><type>Breads</type><fooditem><AvgRating>3.6</AvgRating><Cuisine>Asian</Cuisine><Description>Unleavened flatbread originating from the Indian subcontinent and staple</Description><FoodName>Chappathi</FoodName><ItemCode>R101</ItemCode><PriceForFull>25</PriceForFull><PriceForHalf>9</PriceForHalf><TimeOfServe>Lunch/Dinner</TimeOfServe><Image>chappathi.jpg</Image></fooditem><fooditem><AvgRating>3.6</AvgRating><Cuisine>Kerala</Cuisine><Description>a layered flatbread, originating from the Indian subcontinent, made from maida flour, popular in Southern India.</Description><FoodName>Perotta</FoodName><ItemCode>R102</ItemCode><PriceForFull>40</PriceForFull><PriceForHalf>15</PriceForHalf><TimeOfServe>Lunch/Dinner</TimeOfServe><Image>perotta.jpg</Image></fooditem><fooditem><AvgRating>3.9</AvgRating><Cuisine>South Indian</Cuisine><Description>rice pancake, originating from South India, made from a fermented batter.</Description><FoodName>Dosa</FoodName><ItemCode>R103</ItemCode><PriceForFull>30</PriceForFull><PriceForHalf>8</PriceForHalf><TimeOfServe>Breakfast</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>3.5</AvgRating><Cuisine>Asian</Cuisine><Description>Leavened, oven-baked flatbread found in the cuisines mainly of Western Asia, South Asia, Indonesia, Myanmar and the Caribbean.</Description><FoodName>Naan</FoodName><ItemCode>R104</ItemCode><PriceForFull>50</PriceForFull><PriceForHalf>20</PriceForHalf><TimeOfServe>Dinner</TimeOfServe><Image>naan.jpg</Image></fooditem><fooditem><AvgRating>4.1</AvgRating><Cuisine>North Indian</Cuisine><Description>round flatbread native to the Indian subcontinent made from stoneground wholemeal flour</Description><FoodName>Roti</FoodName><ItemCode>R105</ItemCode><PriceForFull>30</PriceForFull><PriceForHalf>12</PriceForHalf><TimeOfServe>Dinner</TimeOfServe><Image>.</Image></fooditem></category><category><type>Snacks/Tea</type><fooditem><AvgRating>4.8</AvgRating><Cuisine>.</Cuisine><Description>aromatic beverage commonly prepared by pouring hot or boiling water over cured or fresh leaves of the Camellia sinensis</Description><FoodName>Tea</FoodName><ItemCode>S101</ItemCode><PriceForHalf>10</PriceForHalf><PriceForFull>.</PriceForFull><TimeOfServe>Breakfast/Tea</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>4.8</AvgRating><Cuisine>.</Cuisine><Description>Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain Coffea species</Description><FoodName>Coffee</FoodName><ItemCode>S102</ItemCode><PriceForHalf>10</PriceForHalf><PriceForFull>.</PriceForFull><TimeOfServe>Breakfast/Tea</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>4.9</AvgRating><Cuisine>.</Cuisine><Description>You know what is milk. Don't you?</Description><FoodName>Milk</FoodName><ItemCode>S103</ItemCode><PriceForHalf>8</PriceForHalf><PriceForFull>.</PriceForFull><TimeOfServe>Breakfast/Tea</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>4</AvgRating><Cuisine>.</Cuisine><Description>Category of Savoury Fried Snacks</Description><FoodName>Vada</FoodName><ItemCode>S104</ItemCode><PriceForHalf>10</PriceForHalf><PriceForFull>.</PriceForFull><TimeOfServe>Tea</TimeOfServe><Image>.</Image></fooditem><fooditem><AvgRating>3.5</AvgRating><Cuisine>.</Cuisine><Description>Sweet piece made by baking flour, sugar, butter etc.</Description><FoodName>Cake Piece</FoodName><ItemCode>S105</ItemCode><PriceForHalf>8</PriceForHalf><PriceForFull>.</PriceForFull><TimeOfServe>Tea</TimeOfServe><Image>.</Image></fooditem></category></menu>
